source = ['CGSLKPLSC', 'GGSLRPGSS', 'CGGSLRPAC', 'GGSLRPTASS', 'CGSLKPTPSPC', 'SAGSLRPS', 'CGSLKGTAQAPC', 'CHSMADITKGGC', 'RLGGSLSST', 'CGSLRLSSLAF', 'PYRKNPVDGLTP', 'CGSLKGQFQSNC', 'CTDGMPSRLVDVC', 'CGSLKLTPSNSLY', 'CGRLDPFLNC', 'CGGPLRTLSC', 'CSLAGTLRVPC', 'CGSLRACT', 'LCGSLRVCP', 'CGGGSLRTGFNC', 'SLKPTIMTSP', 'CLQLCQVW']
target = ['GGSLRPGSS', 'GGSLRPTASS', 'CGSLRAALLC', 'CGSLKGTAQAPC', 'CHSMADITKGGC', 'CGSLRLSSLAF', 'PYRKNPVDGLTP', 'CASLKPNPEC', 'CDGSTTPSSC', 'CGSLKLTPSNSLY', 'CGRLDPFLNC', 'CGSLKDTSYC', 'CGSLRACT', 'CADSTSPSAL', 'LSNIGPC', 'EPADSPSMLS', 'CYRGMAPQGC']
raw_intersect = ['CGSLKPLSC', 'GGSLRPGSS', 'CGSLKPTPSPC', 'CGSLKGTAQAPC', 'CGSLKLTPSNSLY', 'CGRLDPFLNC', 'CGGPLRTLSC', 'CSLAGTLRVPC', 'LCGSLRVCP']

intersections = [x for x in target if x in source]
print('intersections', intersections)
best_intersections = [x for x in intersections if x in raw_intersect]
print('best', best_intersections)